version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 0
    labels:
      - "dependency"
    open-pull-requests-limit: 5
