language: bash

env:
  - IMAGE=3.6.3-jdk-8 ARGS=-Dair.java.version=1.8
  - IMAGE=3.6.3-jdk-11 ARGS=
  - IMAGE=3.6.3-openjdk-15 ARGS=
  - IMAGE=3.6.3-openjdk-16 ARGS=

install:
  - IMAGE=maven:$IMAGE
  - RUN="run -v $PWD:/build -w /build $IMAGE"
  - docker pull $IMAGE
  - docker $RUN mvn -V -B -q dependency:go-offline $ARGS

script:
  - docker $RUN mvn -V -B clean install $ARGS
